"""ユーザー定義構成などの永続化層（SQLite / PostgreSQL 両対応）。

Phase 2 W6 で導入。当初計画の DynamoDB の代替（AWS 不使用方針 2026-05-07）。

バックエンドは環境変数 ``DATABASE_URL`` で切り替える:

- 未設定 → ローカル開発用の SQLite（``apps/agents/data/results.sqlite3``）
- 設定あり（例: Supabase の接続文字列）→ psycopg3 で PostgreSQL

生 SQL は 1 本で書き、方言差（``?`` プレースホルダ / ``AUTOINCREMENT`` /
``LIKE`` の大小無視 / ``lastrowid`` vs ``RETURNING`` / ``PRAGMA`` vs
``information_schema``）は本モジュール内の薄いラッパ（[_Conn](#) / [_to_pg](#)）で
吸収する。ホスティング移行の全体像は ``docs/deployment-migration-tasks.md`` を参照。

スキーマ:
    saved_configs(id INTEGER, name TEXT UNIQUE, base_config TEXT,
                  overrides_json TEXT, model_overrides_json TEXT,
                  pipeline_json TEXT, created_at TEXT, updated_at TEXT)

- ``overrides_json``: ``{slot_id: 上書きプロンプト}``（config1〜4 用）
- ``model_overrides_json``: ``{slot_id: 上書きモデル名}``（config1〜4 用）
- ``pipeline_json``: ノード定義 JSON 全体（config5 用、UI で組み立てたパイプライン）
slot に上書きが無ければデフォルトが使われる（[prompt_slots.py](prompt_slots.py) 参照）。

ファイルパス: ``apps/agents/data/results.sqlite3``
"""
from __future__ import annotations

import json
import os
import re
import sqlite3
from contextlib import contextmanager
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Iterator

# 環境変数 DATABASE_URL が設定されていれば PostgreSQL、無ければローカル SQLite。
# ホスティング時は Supabase 等の接続文字列を DATABASE_URL に入れる。
_DATABASE_URL = os.environ.get("DATABASE_URL", "").strip()
_BACKEND = "postgres" if _DATABASE_URL else "sqlite"

# api.py から見ても scripts/ から見ても同じ場所に向くように絶対解決（SQLite 時のみ使用）
_DB_PATH = Path(__file__).resolve().parents[2] / "data" / "results.sqlite3"

# psycopg のコネクションプール（postgres 時のみ遅延生成）
_pool: Any = None


def _ensure_dir() -> None:
    if _BACKEND == "sqlite":
        _DB_PATH.parent.mkdir(parents=True, exist_ok=True)


def _to_pg(sql: str) -> str:
    """SQLite 方言で書いた SQL を psycopg（PostgreSQL）用に変換する。

    - ``INTEGER PRIMARY KEY AUTOINCREMENT`` → IDENTITY 列（DDL）
    - 名前付き ``:name`` → ``%(name)s``
    - 位置 ``?`` → ``%s``
    - ``LIKE`` → ``ILIKE``（SQLite の LIKE は ASCII 大小無視なので挙動を揃える）

    対象 SQL には ``?`` / ``:name`` 以外のリテラル ``?`` や ``%`` を含めない前提
    （本モジュール内の SQL はこれを満たす）。
    """
    sql = sql.replace(
        "INTEGER PRIMARY KEY AUTOINCREMENT",
        "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
    )
    sql = re.sub(r":(\w+)", r"%(\1)s", sql)
    sql = sql.replace("?", "%s")
    sql = re.sub(r"\bLIKE\b", "ILIKE", sql)
    return sql


class _Conn:
    """sqlite3.Connection / psycopg.Connection の差を吸収する薄いラッパ。

    ``execute(sql, params)`` は cursor 相当を返し、``.fetchone()`` /
    ``.fetchall()`` / ``.rowcount`` / ``.lastrowid``（SQLite のみ）が使える。
    行は SQLite=``sqlite3.Row`` / PostgreSQL=``dict_row`` で、いずれも
    ``dict(row)`` と ``row["col"]`` が使える（``row[int]`` は SQLite のみ）。
    """

    def __init__(self, raw: Any, backend: str) -> None:
        self._raw = raw
        self.backend = backend

    def execute(self, sql: str, params: Any = ()):  # noqa: ANN401
        if self.backend == "postgres":
            return self._raw.execute(_to_pg(sql), params)
        return self._raw.execute(sql, params)

    def commit(self) -> None:
        self._raw.commit()


def _get_pool() -> Any:
    """PostgreSQL コネクションプールを遅延生成して返す（Supabase pooler 等対応）。"""
    global _pool
    if _pool is None:
        from psycopg.rows import dict_row
        from psycopg_pool import ConnectionPool

        _pool = ConnectionPool(
            _DATABASE_URL,
            kwargs={"row_factory": dict_row},
            min_size=1,
            max_size=int(os.environ.get("DB_POOL_MAX", "10")),
            open=False,
        )
        _pool.open()
    return _pool


def _table_columns(conn: "_Conn", table: str) -> set[str]:
    """テーブルの列名集合を返す（存在しなければ空集合）。マイグレーション判定用。"""
    if conn.backend == "postgres":
        rows = conn.execute(
            "SELECT column_name FROM information_schema.columns WHERE table_name = ?",
            (table,),
        ).fetchall()
        return {r["column_name"] for r in rows}
    rows = conn.execute(f"PRAGMA table_info({table})").fetchall()
    return {r[1] for r in rows}


def _insert_returning_id(conn: "_Conn", sql: str, params: Any) -> int:  # noqa: ANN401
    """INSERT を実行し、生成された id を返す（lastrowid / RETURNING の差を吸収）。"""
    if conn.backend == "postgres":
        row = conn.execute(sql + " RETURNING id", params).fetchone()
        return int(row["id"]) if row else 0
    cur = conn.execute(sql, params)
    return int(cur.lastrowid or 0)


def init_db() -> None:
    """テーブルが無ければ作成（idempotent）。条件付きマイグレーション付き。

    Phase 2 W6 で ``model_overrides_json`` を追加、`feature/visual-pipeline-builder`
    で ``pipeline_json`` を追加、`feature/run-history` で ``run_history`` テーブル追加。
    既存テーブルにカラムが無ければ ALTER TABLE で増やす（保存データは保持）。
    ``model_overrides_json`` が無いさらに古いスキーマだけは DROP して再作成する。
    """
    _ensure_dir()
    with _connect() as conn:
        cols = _table_columns(conn, "saved_configs")
        if cols and "model_overrides_json" not in cols:
            # かなり古いスキーマ → DROP（PoC 期間中の互換性は保証しない）
            conn.execute("DROP TABLE IF EXISTS saved_configs")
            cols = set()
        if not cols:
            conn.execute(
                """
                CREATE TABLE saved_configs (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    name TEXT NOT NULL UNIQUE,
                    base_config TEXT NOT NULL,
                    overrides_json TEXT NOT NULL,
                    model_overrides_json TEXT NOT NULL DEFAULT '{}',
                    pipeline_json TEXT NOT NULL DEFAULT '{}',
                    created_at TEXT NOT NULL,
                    updated_at TEXT NOT NULL
                )
                """
            )
        elif "pipeline_json" not in cols:
            # config5 用カラム追加（ALTER TABLE で既存データ保持）
            conn.execute(
                "ALTER TABLE saved_configs ADD COLUMN pipeline_json TEXT NOT NULL DEFAULT '{}'"
            )
        # 旧 A-2 の saved_prompts テーブルは現スキーマでは不要
        conn.execute("DROP TABLE IF EXISTS saved_prompts")

        # run_history テーブル（実行 1 件 1 行のメタデータのみ。詳細は Langfuse へ）
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS run_history (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                started_at TEXT NOT NULL,
                log_name TEXT NOT NULL,
                config_id TEXT NOT NULL,
                base_config TEXT NOT NULL,
                confidence REAL,
                tokens_in INTEGER,
                tokens_out INTEGER,
                latency_ms INTEGER,
                trace_id TEXT,
                top_category TEXT,
                top_summary TEXT
            )
            """
        )
        conn.execute(
            "CREATE INDEX IF NOT EXISTS idx_run_history_started_at "
            "ON run_history(started_at DESC)"
        )
        conn.execute(
            "CREATE INDEX IF NOT EXISTS idx_run_history_config "
            "ON run_history(config_id)"
        )
        conn.execute(
            "CREATE INDEX IF NOT EXISTS idx_run_history_log "
            "ON run_history(log_name)"
        )

        # questionnaire_templates テーブル (Phase B)
        # items_json は QuestionnaireItem の配列 JSON
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS questionnaire_templates (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                name TEXT NOT NULL UNIQUE,
                description TEXT NOT NULL DEFAULT '',
                items_json TEXT NOT NULL,
                created_at TEXT NOT NULL,
                updated_at TEXT NOT NULL
            )
            """
        )

        # analysis_history テーブル (解析履歴: 完全再現用)
        # 入力 (request_json) + 結果 (result_json) を丸ごと保存し、解析後画面を再現する。
        # 設計: docs/plan/analysis_history.md
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS analysis_history (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                run_id TEXT NOT NULL,
                created_at TEXT NOT NULL,
                kind TEXT NOT NULL DEFAULT 'config-log',
                config_id TEXT NOT NULL,
                analysis_mode TEXT,
                single_source TEXT,
                stage_order TEXT,
                title TEXT,
                confidence REAL,
                tokens_in INTEGER,
                tokens_out INTEGER,
                latency_ms INTEGER,
                top_category TEXT,
                top_summary TEXT,
                trace_id TEXT,
                request_json TEXT NOT NULL,
                result_json TEXT NOT NULL
            )
            """
        )
        conn.execute(
            "CREATE UNIQUE INDEX IF NOT EXISTS idx_analysis_history_run "
            "ON analysis_history(run_id)"
        )
        conn.execute(
            "CREATE INDEX IF NOT EXISTS idx_analysis_history_created "
            "ON analysis_history(created_at DESC)"
        )
        # answer_scenarios テーブル (解析評価の正解データ: Excel「テストケース2」D-K列から取込)
        # scenario_key はグループ単位 (A〜N)。①〜⑦＋補足を保持し、⑥(conclusion)=真因が
        # 採点の主軸。設計: [[project_accuracy_cost_2026-07-01]] / reference_ibc_testcase_excel
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS answer_scenarios (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                scenario_key TEXT NOT NULL UNIQUE,
                title TEXT NOT NULL DEFAULT '',
                trigger TEXT NOT NULL DEFAULT '',
                initial_hypothesis TEXT NOT NULL DEFAULT '',
                path TEXT NOT NULL DEFAULT '',
                decision_points TEXT NOT NULL DEFAULT '',
                evidence_source TEXT NOT NULL DEFAULT '',
                conclusion TEXT NOT NULL DEFAULT '',
                junior_pitfall TEXT NOT NULL DEFAULT '',
                notes TEXT NOT NULL DEFAULT '',
                source_file TEXT NOT NULL DEFAULT '',
                imported_at TEXT NOT NULL
            )
            """
        )

        # analysis_evaluations テーブル (解析レポート × 解答 の評価結果、履歴に紐付け)
        # 1 履歴に複数評価を許可 (別シナリオ / 再評価は追記して全部残す)。
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS analysis_evaluations (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                analysis_history_id INTEGER NOT NULL,
                scenario_key TEXT NOT NULL,
                score INTEGER,
                axis_assessment_json TEXT NOT NULL DEFAULT '[]',
                good_points_json TEXT NOT NULL DEFAULT '[]',
                bad_points_json TEXT NOT NULL DEFAULT '[]',
                pitfalls_avoided_json TEXT NOT NULL DEFAULT '[]',
                pitfalls_hit_json TEXT NOT NULL DEFAULT '[]',
                summary TEXT NOT NULL DEFAULT '',
                model TEXT NOT NULL DEFAULT '',
                tokens_in INTEGER,
                tokens_out INTEGER,
                latency_ms INTEGER,
                created_at TEXT NOT NULL
            )
            """
        )
        # 既存 DB へのマイグレーション: axis_assessment_json (採点根拠) 列を後付け。
        ev_cols = _table_columns(conn, "analysis_evaluations")
        if ev_cols and "axis_assessment_json" not in ev_cols:
            conn.execute(
                "ALTER TABLE analysis_evaluations "
                "ADD COLUMN axis_assessment_json TEXT NOT NULL DEFAULT '[]'"
            )
        conn.execute(
            "CREATE INDEX IF NOT EXISTS idx_analysis_evaluations_history "
            "ON analysis_evaluations(analysis_history_id, created_at DESC)"
        )
        conn.commit()

        # デフォルトテンプレを idempotent に投入 (初回起動時のみ)
        _ensure_default_questionnaire(conn)
        conn.commit()


_DEFAULT_QUESTIONNAIRE_NAME = "default"
# 障害状況問診票 (2026-07 改訂)。key は日本語フィールド名 = プロンプトが参照する呼称。
# log_text の問診票ブロックは `- **{key}**: {answer}` で描画されるため、key を
# そのまま LLM が読む (プランナー/監視/統合の「②まだ確認していないこと」「③いま一番
# 迷っていること」等の参照と一致させる)。必須度は required(bool)へ写像 (必須→True)。
_DEFAULT_QUESTIONNAIRE_ITEMS: list[dict] = [
    {"key": "事象", "label": "【事象】何が起きているか／発生頻度は？",
     "type": "textarea", "options": [],
     "placeholder": "何が・誰に・どんな症状か、発生頻度はどうか。1〜2文で。（必須）", "required": True},
    {"key": "いつから（その前は正常だったか）", "label": "【①変化点】いつから／その前は正常だったか",
     "type": "textarea", "options": [],
     "placeholder": "「昨日まで正常→今朝から」のように前後で書く。目安でよい。（必須）", "required": True},
    {"key": "その頃に変わったこと", "label": "【①変化点】その頃に変わったこと",
     "type": "textarea", "options": [],
     "placeholder": "設定変更・更新・新規利用・人員/拠点の変化など。心当たりなければ『なし』。（推奨）",
     "required": False},
    {"key": "影響を受ける対象と、受けない対象", "label": "【②対照・否定】影響を受ける／受けない対象",
     "type": "textarea", "options": [],
     "placeholder": "『Aは起きるがBは大丈夫』の対で。例：無線NG/有線OK、3Fだけ、午前だけ、特定アプリだけ。（必須）",
     "required": True},
    {"key": "確認して問題なかったこと", "label": "【②対照・否定】確認して問題なかったこと",
     "type": "textarea", "options": [],
     "placeholder": "自分で確認してOKだったこと（＝確定した手がかり）。（推奨）", "required": False},
    {"key": "まだ確認していないこと", "label": "【②対照・否定】まだ確認していないこと",
     "type": "textarea", "options": [],
     "placeholder": "未確認のもの。『正常』とは区別して書く。（推奨）", "required": False},
    {"key": "原因の見当", "label": "【③見立て】原因の見当",
     "type": "textarea", "options": [],
     "placeholder": "思い当たる原因。なければ空欄でよい。（任意）", "required": False},
    {"key": "やろうとしている打ち手", "label": "【③打ち手】やろうとしている打ち手",
     "type": "textarea", "options": [],
     "placeholder": "やりたい対処。なければ空欄でよい。（任意）", "required": False},
    {"key": "いま一番迷っていること", "label": "【③迷い】いま一番迷っていること",
     "type": "textarea", "options": [],
     "placeholder": "うまく決められない・進められない点をそのまま書く。ここが相談の核。（推奨）",
     "required": False},
]

# 新問診票のキー集合と、旧デフォルト特有キー (アップグレード判定用)
_NEW_DEFAULT_KEYS = {it["key"] for it in _DEFAULT_QUESTIONNAIRE_ITEMS}
_OLD_DEFAULT_MARKER_KEYS = {"occurred_at", "has_topology_diagram", "trigger_action", "event"}


def _ensure_default_questionnaire(conn: "_Conn") -> None:
    """name='default' のテンプレを新問診票 (障害状況問診票) に揃える。

    - 無ければ新問診票で作成。
    - 既存が旧デフォルト構造 (occurred_at / has_topology_diagram 等を含む) なら
      新問診票へ置き換える (2026-07 改訂。PoC 期間中の旧互換は保証しない方針)。
    - 上記以外 (利用者が独自に編集した default) は触らない。
    """
    row = conn.execute(
        "SELECT id, items_json FROM questionnaire_templates WHERE name = ?",
        (_DEFAULT_QUESTIONNAIRE_NAME,),
    ).fetchone()
    now = _now_iso()
    payload = json.dumps(_DEFAULT_QUESTIONNAIRE_ITEMS, ensure_ascii=False)
    if row is None:
        conn.execute(
            "INSERT INTO questionnaire_templates "
            "(name, description, items_json, created_at, updated_at) VALUES (?, ?, ?, ?, ?)",
            (_DEFAULT_QUESTIONNAIRE_NAME, "障害状況問診票", payload, now, now),
        )
        return
    raw_items = row["items_json"]
    try:
        items = json.loads(raw_items) if raw_items else []
    except Exception:  # noqa: BLE001
        items = []
    keys = {it.get("key") for it in items if isinstance(it, dict)}
    if keys == _NEW_DEFAULT_KEYS:
        return  # 既に新問診票
    # 旧デフォルト構造なら新問診票へアップグレード
    if keys & _OLD_DEFAULT_MARKER_KEYS:
        conn.execute(
            "UPDATE questionnaire_templates SET items_json = ?, description = ?, updated_at = ? "
            "WHERE id = ?",
            (payload, "障害状況問診票", now, row["id"]),
        )


@contextmanager
def _connect() -> Iterator["_Conn"]:
    if _BACKEND == "postgres":
        # pool.connection() は正常終了で commit / 例外で rollback してから返却する。
        with _get_pool().connection() as raw:
            yield _Conn(raw, "postgres")
        return
    _ensure_dir()
    raw = sqlite3.connect(_DB_PATH)
    raw.row_factory = sqlite3.Row
    try:
        yield _Conn(raw, "sqlite")
    finally:
        raw.close()


def _now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


def _row_to_config(row: Any) -> dict:
    d = dict(row)
    raw_p = d.pop("overrides_json")
    raw_m = d.pop("model_overrides_json", None)
    raw_pipe = d.pop("pipeline_json", None)
    d["overrides"] = json.loads(raw_p) if raw_p else {}
    d["model_overrides"] = json.loads(raw_m) if raw_m else {}
    d["pipeline"] = json.loads(raw_pipe) if raw_pipe and raw_pipe != "{}" else None
    return d


_COLS = (
    "id, name, base_config, overrides_json, model_overrides_json, pipeline_json, "
    "created_at, updated_at"
)


def list_saved_configs() -> list[dict]:
    with _connect() as conn:
        rows = conn.execute(
            f"SELECT {_COLS} FROM saved_configs ORDER BY updated_at DESC"
        ).fetchall()
    return [_row_to_config(r) for r in rows]


def get_saved_config(config_id: int) -> dict | None:
    with _connect() as conn:
        row = conn.execute(
            f"SELECT {_COLS} FROM saved_configs WHERE id = ?",
            (config_id,),
        ).fetchone()
    return _row_to_config(row) if row else None


def create_saved_config(
    name: str,
    base_config: str,
    overrides: dict[str, str],
    model_overrides: dict[str, str] | None = None,
    pipeline: dict | None = None,
) -> dict:
    now = _now_iso()
    p = json.dumps(overrides, ensure_ascii=False)
    m = json.dumps(model_overrides or {}, ensure_ascii=False)
    pipe = json.dumps(pipeline or {}, ensure_ascii=False) if pipeline else "{}"
    with _connect() as conn:
        config_id = _insert_returning_id(
            conn,
            "INSERT INTO saved_configs (name, base_config, overrides_json, model_overrides_json, "
            "pipeline_json, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?)",
            (name, base_config, p, m, pipe, now, now),
        )
        conn.commit()
    saved = get_saved_config(config_id) if config_id else None
    if saved is None:
        raise RuntimeError("failed to retrieve saved config after insert")
    return saved


def update_saved_config(
    config_id: int,
    overrides: dict[str, str],
    model_overrides: dict[str, str] | None = None,
    pipeline: dict | None = None,
) -> dict | None:
    now = _now_iso()
    p = json.dumps(overrides, ensure_ascii=False)
    m = json.dumps(model_overrides or {}, ensure_ascii=False)
    pipe = json.dumps(pipeline or {}, ensure_ascii=False) if pipeline else "{}"
    with _connect() as conn:
        cursor = conn.execute(
            "UPDATE saved_configs SET overrides_json = ?, model_overrides_json = ?, "
            "pipeline_json = ?, updated_at = ? WHERE id = ?",
            (p, m, pipe, now, config_id),
        )
        conn.commit()
        if cursor.rowcount == 0:
            return None
    return get_saved_config(config_id)


def delete_saved_config(config_id: int) -> bool:
    with _connect() as conn:
        cursor = conn.execute("DELETE FROM saved_configs WHERE id = ?", (config_id,))
        conn.commit()
        return cursor.rowcount > 0


# ─── run_history ─────────────────────────────────────────────────────


_RUN_COLS = (
    "id, started_at, log_name, config_id, base_config, confidence, "
    "tokens_in, tokens_out, latency_ms, trace_id, top_category, top_summary"
)


def insert_run_history(
    *,
    log_name: str,
    config_id: str,
    base_config: str,
    confidence: float | None,
    tokens_in: int | None,
    tokens_out: int | None,
    latency_ms: int | None,
    trace_id: str | None,
    top_category: str | None,
    top_summary: str | None,
    started_at: str | None = None,
) -> int:
    """実行 1 件分のメタデータを記録し、行 ID を返す。"""
    when = started_at or _now_iso()
    with _connect() as conn:
        new_id = _insert_returning_id(
            conn,
            "INSERT INTO run_history (started_at, log_name, config_id, base_config, "
            "confidence, tokens_in, tokens_out, latency_ms, trace_id, top_category, top_summary) "
            "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)",
            (
                when, log_name, config_id, base_config, confidence,
                tokens_in, tokens_out, latency_ms, trace_id, top_category, top_summary,
            ),
        )
        conn.commit()
        return new_id


def list_run_history(
    *,
    log_name: str | None = None,
    config_id: str | None = None,
    base_config: str | None = None,
    q: str | None = None,
    limit: int = 200,
    offset: int = 0,
) -> tuple[list[dict], int]:
    """フィルタ付きで一覧を返す。``(rows, total_count)`` のタプル。

    - ``log_name`` / ``config_id`` / ``base_config``: 完全一致
    - ``q``: top_summary に部分一致
    """
    where: list[str] = []
    args: list = []
    if log_name:
        where.append("log_name = ?")
        args.append(log_name)
    if config_id:
        where.append("config_id = ?")
        args.append(config_id)
    if base_config:
        where.append("base_config = ?")
        args.append(base_config)
    if q:
        where.append("(top_summary LIKE ? OR log_name LIKE ?)")
        like = f"%{q}%"
        args.extend([like, like])
    where_sql = (" WHERE " + " AND ".join(where)) if where else ""

    with _connect() as conn:
        total = conn.execute(
            f"SELECT COUNT(*) AS n FROM run_history{where_sql}", args
        ).fetchone()["n"]
        rows = conn.execute(
            f"SELECT {_RUN_COLS} FROM run_history{where_sql} "
            f"ORDER BY started_at DESC LIMIT ? OFFSET ?",
            (*args, limit, offset),
        ).fetchall()
    return [dict(r) for r in rows], int(total)


def get_run_history(run_id: int) -> dict | None:
    with _connect() as conn:
        row = conn.execute(
            f"SELECT {_RUN_COLS} FROM run_history WHERE id = ?", (run_id,)
        ).fetchone()
    return dict(row) if row else None


def delete_run_history(run_id: int) -> bool:
    with _connect() as conn:
        cursor = conn.execute("DELETE FROM run_history WHERE id = ?", (run_id,))
        conn.commit()
        return cursor.rowcount > 0


# ─── analysis_history (解析履歴: 完全再現用) ──────────────────────

# 一覧で返すサマリ列 (重い JSON は含めない)
_ANALYSIS_SUMMARY_COLS = (
    "id, run_id, created_at, kind, config_id, analysis_mode, single_source, stage_order, "
    "title, confidence, tokens_in, tokens_out, latency_ms, top_category, top_summary, trace_id"
)


def insert_analysis_history(
    *,
    run_id: str,
    kind: str,
    config_id: str,
    analysis_mode: str | None,
    single_source: str | None,
    stage_order: str | None,
    title: str | None,
    confidence: float | None,
    tokens_in: int | None,
    tokens_out: int | None,
    latency_ms: int | None,
    top_category: str | None,
    top_summary: str | None,
    trace_id: str | None,
    request_json: str,
    result_json: str,
    created_at: str | None = None,
) -> tuple[int, bool]:
    """解析履歴を 1 件保存し、``(id, created)`` を返す。

    同一 ``run_id`` が既にあれば挿入せず ``created=False`` と既存 id を返す (no-op)。
    """
    with _connect() as conn:
        existing = conn.execute(
            "SELECT id FROM analysis_history WHERE run_id = ?", (run_id,)
        ).fetchone()
        if existing is not None:
            return int(existing["id"]), False
        when = created_at or _now_iso()
        new_id = _insert_returning_id(
            conn,
            "INSERT INTO analysis_history "
            "(run_id, created_at, kind, config_id, analysis_mode, single_source, stage_order, "
            " title, confidence, tokens_in, tokens_out, latency_ms, top_category, top_summary, "
            " trace_id, request_json, result_json) "
            "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)",
            (
                run_id, when, kind, config_id, analysis_mode, single_source, stage_order,
                title, confidence, tokens_in, tokens_out, latency_ms, top_category, top_summary,
                trace_id, request_json, result_json,
            ),
        )
        conn.commit()
        return new_id, True


def list_analysis_history(
    *,
    kind: str | None = None,
    analysis_mode: str | None = None,
    q: str | None = None,
    limit: int = 200,
    offset: int = 0,
) -> tuple[list[dict], int]:
    """フィルタ付きで一覧（サマリのみ）を返す。``(rows, total_count)``。"""
    where: list[str] = []
    args: list = []
    if kind:
        where.append("kind = ?")
        args.append(kind)
    if analysis_mode:
        where.append("analysis_mode = ?")
        args.append(analysis_mode)
    if q:
        # top_summary / title に加え、解析結果本体 (result_json) も対象にする。
        # 候補 summary / evidence / 委譲理由などは result_json 内にしか無いため、
        # ここを含めないと本文テキストで検索してもヒットしない。
        where.append("(top_summary LIKE ? OR title LIKE ? OR result_json LIKE ?)")
        like = f"%{q}%"
        args.extend([like, like, like])
    where_sql = (" WHERE " + " AND ".join(where)) if where else ""
    with _connect() as conn:
        total = conn.execute(
            f"SELECT COUNT(*) AS n FROM analysis_history{where_sql}", args
        ).fetchone()["n"]
        rows = conn.execute(
            f"SELECT {_ANALYSIS_SUMMARY_COLS} FROM analysis_history{where_sql} "
            f"ORDER BY created_at DESC LIMIT ? OFFSET ?",
            (*args, limit, offset),
        ).fetchall()
    return [dict(r) for r in rows], int(total)


def get_analysis_history(entry_id: int) -> dict | None:
    """個別取得。``request`` / ``result`` を JSON パースして返す（完全再現用）。"""
    with _connect() as conn:
        row = conn.execute(
            "SELECT * FROM analysis_history WHERE id = ?", (entry_id,)
        ).fetchone()
    if row is None:
        return None
    d = dict(row)
    raw_req = d.pop("request_json", None)
    raw_res = d.pop("result_json", None)
    d["request"] = json.loads(raw_req) if raw_req else {}
    d["result"] = json.loads(raw_res) if raw_res else {}
    return d


def delete_analysis_history(entry_id: int) -> bool:
    with _connect() as conn:
        cursor = conn.execute("DELETE FROM analysis_history WHERE id = ?", (entry_id,))
        conn.commit()
        return cursor.rowcount > 0


# ─── answer_scenarios (解析評価の正解データ) ──────────────────────

_ANSWER_COLS = (
    "id, scenario_key, title, trigger, initial_hypothesis, path, decision_points, "
    "evidence_source, conclusion, junior_pitfall, notes, source_file, imported_at"
)

# 取込時に受け付ける本文フィールド (scenario_key/source_file 以外)
_ANSWER_BODY_FIELDS = (
    "title", "trigger", "initial_hypothesis", "path", "decision_points",
    "evidence_source", "conclusion", "junior_pitfall", "notes",
)


def upsert_answer_scenario(
    scenario_key: str,
    *,
    source_file: str = "",
    **fields: str,
) -> dict:
    """scenario_key で解答シナリオを upsert (既存なら本文を上書き)。

    Excel は Drive 管理で取込直しがあるため、常に scenario_key 一意で上書きする。
    ``fields`` は ``_ANSWER_BODY_FIELDS`` のいずれか (未指定は空文字)。
    """
    key = str(scenario_key).strip()
    if not key:
        raise ValueError("scenario_key は必須")
    body = {f: str(fields.get(f, "") or "") for f in _ANSWER_BODY_FIELDS}
    now = _now_iso()
    with _connect() as conn:
        conn.execute(
            "INSERT INTO answer_scenarios "
            "(scenario_key, title, trigger, initial_hypothesis, path, decision_points, "
            " evidence_source, conclusion, junior_pitfall, notes, source_file, imported_at) "
            "VALUES (:scenario_key, :title, :trigger, :initial_hypothesis, :path, "
            " :decision_points, :evidence_source, :conclusion, :junior_pitfall, :notes, "
            " :source_file, :imported_at) "
            "ON CONFLICT(scenario_key) DO UPDATE SET "
            " title=excluded.title, trigger=excluded.trigger, "
            " initial_hypothesis=excluded.initial_hypothesis, path=excluded.path, "
            " decision_points=excluded.decision_points, evidence_source=excluded.evidence_source, "
            " conclusion=excluded.conclusion, junior_pitfall=excluded.junior_pitfall, "
            " notes=excluded.notes, source_file=excluded.source_file, "
            " imported_at=excluded.imported_at",
            {"scenario_key": key, "source_file": source_file, "imported_at": now, **body},
        )
        conn.commit()
    saved = get_answer_scenario(key)
    if saved is None:
        raise RuntimeError("failed to retrieve answer scenario after upsert")
    return saved


def list_answer_scenarios() -> list[dict]:
    with _connect() as conn:
        rows = conn.execute(
            f"SELECT {_ANSWER_COLS} FROM answer_scenarios ORDER BY scenario_key ASC"
        ).fetchall()
    return [dict(r) for r in rows]


def get_answer_scenario(scenario_key: str) -> dict | None:
    with _connect() as conn:
        row = conn.execute(
            f"SELECT {_ANSWER_COLS} FROM answer_scenarios WHERE scenario_key = ?",
            (str(scenario_key).strip(),),
        ).fetchone()
    return dict(row) if row else None


def delete_answer_scenario(scenario_key: str) -> bool:
    with _connect() as conn:
        cursor = conn.execute(
            "DELETE FROM answer_scenarios WHERE scenario_key = ?",
            (str(scenario_key).strip(),),
        )
        conn.commit()
        return cursor.rowcount > 0


# ─── analysis_evaluations (解析レポート × 解答 の評価結果) ──────────

_EVAL_COLS = (
    "id, analysis_history_id, scenario_key, score, axis_assessment_json, good_points_json, "
    "bad_points_json, pitfalls_avoided_json, pitfalls_hit_json, summary, model, tokens_in, "
    "tokens_out, latency_ms, created_at"
)
_EVAL_LIST_FIELDS = (
    "axis_assessment", "good_points", "bad_points", "pitfalls_avoided", "pitfalls_hit",
)


def _row_to_evaluation(row: Any) -> dict:
    d = dict(row)
    for f in _EVAL_LIST_FIELDS:
        raw = d.pop(f"{f}_json", None)
        try:
            d[f] = json.loads(raw) if raw else []
        except Exception:  # noqa: BLE001
            d[f] = []
    return d


def insert_evaluation(
    *,
    analysis_history_id: int,
    scenario_key: str,
    score: int | None,
    axis_assessment: list[str],
    good_points: list[str],
    bad_points: list[str],
    pitfalls_avoided: list[str],
    pitfalls_hit: list[str],
    summary: str,
    model: str,
    tokens_in: int | None = None,
    tokens_out: int | None = None,
    latency_ms: int | None = None,
) -> dict:
    """評価を 1 件保存し、保存後の行 (リストはパース済み) を返す。"""
    now = _now_iso()

    def _j(v: list[str]) -> str:
        return json.dumps([str(x) for x in (v or [])], ensure_ascii=False)

    with _connect() as conn:
        eval_id = _insert_returning_id(
            conn,
            "INSERT INTO analysis_evaluations "
            "(analysis_history_id, scenario_key, score, axis_assessment_json, good_points_json, "
            " bad_points_json, pitfalls_avoided_json, pitfalls_hit_json, summary, model, "
            " tokens_in, tokens_out, latency_ms, created_at) "
            "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)",
            (
                analysis_history_id, str(scenario_key), score, _j(axis_assessment),
                _j(good_points), _j(bad_points), _j(pitfalls_avoided), _j(pitfalls_hit),
                summary, model, tokens_in, tokens_out, latency_ms, now,
            ),
        )
        conn.commit()
    saved = get_evaluation(eval_id)
    if saved is None:
        raise RuntimeError("failed to retrieve evaluation after insert")
    return saved


def get_evaluation(eval_id: int) -> dict | None:
    with _connect() as conn:
        row = conn.execute(
            f"SELECT {_EVAL_COLS} FROM analysis_evaluations WHERE id = ?", (eval_id,)
        ).fetchone()
    return _row_to_evaluation(row) if row else None


def list_evaluations(analysis_history_id: int) -> list[dict]:
    """指定履歴に紐付く評価を新しい順で返す (後から確認用)。"""
    with _connect() as conn:
        rows = conn.execute(
            f"SELECT {_EVAL_COLS} FROM analysis_evaluations "
            "WHERE analysis_history_id = ? ORDER BY created_at DESC, id DESC",
            (analysis_history_id,),
        ).fetchall()
    return [_row_to_evaluation(r) for r in rows]


def delete_evaluation(eval_id: int) -> bool:
    with _connect() as conn:
        cursor = conn.execute(
            "DELETE FROM analysis_evaluations WHERE id = ?", (eval_id,)
        )
        conn.commit()
        return cursor.rowcount > 0


# ─── 問診票テンプレート CRUD (Phase B) ──────────────────────────

_QUESTIONNAIRE_COLS = "id, name, description, items_json, created_at, updated_at"


def _row_to_questionnaire(row: Any) -> dict:
    d = dict(row)
    raw = d.pop("items_json", None)
    d["items"] = json.loads(raw) if raw else []
    return d


def list_questionnaires() -> list[dict]:
    with _connect() as conn:
        rows = conn.execute(
            f"SELECT {_QUESTIONNAIRE_COLS} FROM questionnaire_templates ORDER BY updated_at DESC"
        ).fetchall()
    return [_row_to_questionnaire(r) for r in rows]


def get_questionnaire(qid: int) -> dict | None:
    with _connect() as conn:
        row = conn.execute(
            f"SELECT {_QUESTIONNAIRE_COLS} FROM questionnaire_templates WHERE id = ?",
            (qid,),
        ).fetchone()
    return _row_to_questionnaire(row) if row else None


def create_questionnaire(name: str, description: str, items: list[dict]) -> dict:
    if not name.strip():
        raise ValueError("name は必須")
    now = _now_iso()
    payload = json.dumps(items, ensure_ascii=False)
    with _connect() as conn:
        qid = _insert_returning_id(
            conn,
            "INSERT INTO questionnaire_templates "
            "(name, description, items_json, created_at, updated_at) VALUES (?, ?, ?, ?, ?)",
            (name.strip(), description or "", payload, now, now),
        )
        conn.commit()
    saved = get_questionnaire(qid) if qid else None
    if saved is None:
        raise RuntimeError("failed to retrieve questionnaire after insert")
    return saved


def update_questionnaire(qid: int, description: str | None, items: list[dict]) -> dict | None:
    """description は None なら据置、items は常に上書き。name は不変 (rename 不可)。"""
    now = _now_iso()
    payload = json.dumps(items, ensure_ascii=False)
    with _connect() as conn:
        if description is None:
            cursor = conn.execute(
                "UPDATE questionnaire_templates SET items_json = ?, updated_at = ? WHERE id = ?",
                (payload, now, qid),
            )
        else:
            cursor = conn.execute(
                "UPDATE questionnaire_templates SET description = ?, items_json = ?, updated_at = ? WHERE id = ?",
                (description, payload, now, qid),
            )
        conn.commit()
        if cursor.rowcount == 0:
            return None
    return get_questionnaire(qid)


def delete_questionnaire(qid: int) -> bool:
    """default テンプレ (name='default') は削除不可。"""
    existing = get_questionnaire(qid)
    if existing is None:
        return False
    if existing["name"] == _DEFAULT_QUESTIONNAIRE_NAME:
        raise ValueError("default テンプレは削除できません")
    with _connect() as conn:
        cursor = conn.execute("DELETE FROM questionnaire_templates WHERE id = ?", (qid,))
        conn.commit()
        return cursor.rowcount > 0
